import { eq } from "drizzle-orm";
import { canAccessFront, canAccessOrganization, canAccessProject, canItem } from "../../../db/authorization";
import { departments, fronts, products, projects, teams } from "../../../db/schema";
import type { ensurePersonalContext } from "../../../db/current-user";

export const productStatuses = ["planned", "todo", "in_progress", "awaiting_approval", "completed", "cancelled", "archived"] as const;
export const productSizes = ["xs", "s", "m", "l", "xl"] as const;
export const productPriorities = ["low", "medium", "high"] as const;
export type ProductParentType = "organization" | "department" | "team" | "project" | "front" | null;
type Context = NonNullable<Awaited<ReturnType<typeof ensurePersonalContext>>>;
export const cleanProductCharacteristics = (value: unknown): { key: string; value: string }[] | null => { if (!Array.isArray(value) || value.length > 30) return null; const items = value.map((item) => ({ key: typeof item?.key === "string" ? item.key.trim().replace(/\s+/g, " ") : "", value: typeof item?.value === "string" ? item.value.trim().replace(/\s+/g, " ") : "" })).filter((item) => item.key || item.value); return items.some((item) => !item.key || !item.value || item.key.length > 80 || item.value.length > 240) ? null : items; };
export const productResponse = (product: typeof products.$inferSelect) => ({ ...product, characteristics: (() => { try { const value = JSON.parse(product.characteristicsJson); return Array.isArray(value) ? value : []; } catch { return []; } })() });
export async function targetForProduct(context: Context, parentType: ProductParentType, parentId: string | null) { if (!parentType && !parentId) return { organizationId: null, allowed: true }; if (!parentType || !parentId) return { organizationId: null, allowed: false }; if (parentType === "organization") return { organizationId: parentId, allowed: await canAccessOrganization(context.db, context.user.id, context.user.email, parentId, "add_children") }; if (parentType === "project") { const [parent] = await context.db.select().from(projects).where(eq(projects.id, parentId)).limit(1); return { organizationId: parent?.organizationId ?? null, allowed: Boolean(parent && await canAccessProject(context.db, context.user.id, parentId, context.space.id, "add_children")) }; } if (parentType === "front") { const [parent] = await context.db.select().from(fronts).where(eq(fronts.id, parentId)).limit(1); return { organizationId: parent?.organizationId ?? null, allowed: Boolean(parent && await canAccessFront(context.db, context.user.id, parentId, context.space.id, "add_children")) }; } const table = parentType === "department" ? departments : teams; const [parent] = await context.db.select().from(table).where(eq(table.id, parentId)).limit(1); return { organizationId: parent?.organizationId ?? null, allowed: Boolean(parent && (parent.ownerUserId === context.user.id || await canItem(context.db, context.user.id, parentType, parentId, "add_children") || (parent.organizationId !== null && await canAccessOrganization(context.db, context.user.id, context.user.email, parent.organizationId, "add_children")))) }; }
