import { eq } from "drizzle-orm";
import { canAccessFront, canAccessOrganization, canAccessProduct, canAccessProject, canItem } from "../../../db/authorization";
import { departments, fronts, processes, products, projects, teams } from "../../../db/schema";
import type { ensurePersonalContext } from "../../../db/current-user";

export const processStatuses = ["planned", "todo", "in_progress", "awaiting_approval", "completed", "cancelled", "archived"] as const;
export const processSizes = ["xs", "s", "m", "l", "xl"] as const;
export const processPriorities = ["low", "medium", "high"] as const;
export type ProcessParentType = "organization" | "department" | "team" | "project" | "front" | "product" | null;
type Context = NonNullable<Awaited<ReturnType<typeof ensurePersonalContext>>>;
export async function targetForProcess(context: Context, parentType: ProcessParentType, parentId: string | null) { if (!parentType && !parentId) return { organizationId: null, allowed: true }; if (!parentType || !parentId) return { organizationId: null, allowed: false }; if (parentType === "organization") return { organizationId: parentId, allowed: await canAccessOrganization(context.db, context.user.id, context.user.email, parentId, "add_children") }; if (parentType === "project") { const [p] = await context.db.select().from(projects).where(eq(projects.id, parentId)).limit(1); return { organizationId: p?.organizationId ?? null, allowed: Boolean(p && await canAccessProject(context.db, context.user.id, parentId, context.space.id, "add_children")) }; } if (parentType === "front") { const [p] = await context.db.select().from(fronts).where(eq(fronts.id, parentId)).limit(1); return { organizationId: p?.organizationId ?? null, allowed: Boolean(p && await canAccessFront(context.db, context.user.id, parentId, context.space.id, "add_children")) }; } if (parentType === "product") { const [p] = await context.db.select().from(products).where(eq(products.id, parentId)).limit(1); return { organizationId: p?.organizationId ?? null, allowed: Boolean(p && await canAccessProduct(context.db, context.user.id, parentId, context.space.id, "add_children")) }; } const table = parentType === "department" ? departments : teams; const [p] = await context.db.select().from(table).where(eq(table.id, parentId)).limit(1); return { organizationId: p?.organizationId ?? null, allowed: Boolean(p && (p.ownerUserId === context.user.id || await canItem(context.db, context.user.id, parentType, parentId, "add_children") || (p.organizationId !== null && await canAccessOrganization(context.db, context.user.id, context.user.email, p.organizationId, "add_children")))) }; }
export const processResponse = (process: typeof processes.$inferSelect) => ({ ...process, phaseSupport: "Preparado para Fases, tarefas diretas, dependências e conclusão automática em fase posterior." });
